//  bst_ip.h : précisions sur l'implantation du module bst.

//  bst_empty : temps ... ; espace ...

//  bst_dispose : temps ... ; espace ...

//  bst_add_endofpath : temps ... ; espace ...

//  bst_remove_climbup_left : temps ... ; espace ...

//  bst_search : temps ... ; espace ...

//  bst_size : temps ... ; espace ...

//  bst_height : temps ... ; espace ...

//  bst_distance : temps ... ; espace ...

//  bst_number : temps ... ; espace ...

//  bst_rank : temps ... ; espace ...

//  bst_repr_graphic : temps ... ; espace ...

//  bst_dft_infix_apply_context : temps ... ; espace ...
